#!/usr/bin/env bash
python src_joint/main.py train \
 --model-path-base models/hpsg_vn \
 --epochs 100 \
 --use-xlnet \
 --use-tags \
 --const-lada 0.5 \
 --dataset ptb \
 --embedding-path data/glove.gz \
 --model-name hpsg_vn \
 --checks-per-epoch 4 \
 --num-layers 3 \
 --learning-rate 0.00005 \
 --batch-size 100 \
 --eval-batch-size 20 \
 --subbatch-max-tokens 1000 \
 --train-ptb-path data/cp_train_vn.txt \
 --dev-ptb-path data/cp_dev_vn.txt \
 --dep-train-ptb-path data/dp_train_vn.txt \
 --dep-dev-ptb-path data/dp_dev_vn.txt \
 --lal-d-kv 128 \
 --lal-d-proj 128 \
 --no-lal-resdrop
